/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OpenclawRouteImport } from './routes/openclaw'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as PortalTokenRouteImport } from './routes/portal.$token'
import { Route as HelpImportTransactionsViaGoogleSheetsRouteImport } from './routes/help/import-transactions-via-google-sheets'
import { Route as DownloadMacRouteImport } from './routes/download.mac'
import { Route as BillingReturnRouteImport } from './routes/billing.return'
import { Route as AuthDesktopRouteImport } from './routes/auth.desktop'
import { Route as AgentsStitchRouteImport } from './routes/agents/stitch'
import { Route as AgentsSkillsRouteImport } from './routes/agents/skills'
import { Route as AgentsClaudeRouteImport } from './routes/agents/claude'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedNewProjectRouteImport } from './routes/_authed/new-project'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedProjectIdRouteImport } from './routes/_authed/project.$id'
import { Route as PortalTokenTaskTaskIdRouteImport } from './routes/portal.$token.task.$taskId'
import { Route as AuthedProjectIdStitchRouteImport } from './routes/_authed/project.$id.stitch'
import { Route as AuthedProjectIdTaskTaskIdRouteImport } from './routes/_authed/project.$id.task.$taskId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenclawRoute = OpenclawRouteImport.update({
  id: '/openclaw',
  path: '/openclaw',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentsRoute,
} as any)
const PortalTokenRoute = PortalTokenRouteImport.update({
  id: '/portal/$token',
  path: '/portal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpImportTransactionsViaGoogleSheetsRoute =
  HelpImportTransactionsViaGoogleSheetsRouteImport.update({
    id: '/help/import-transactions-via-google-sheets',
    path: '/help/import-transactions-via-google-sheets',
    getParentRoute: () => rootRouteImport,
  } as any)
const DownloadMacRoute = DownloadMacRouteImport.update({
  id: '/download/mac',
  path: '/download/mac',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingReturnRoute = BillingReturnRouteImport.update({
  id: '/billing/return',
  path: '/billing/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDesktopRoute = AuthDesktopRouteImport.update({
  id: '/desktop',
  path: '/desktop',
  getParentRoute: () => AuthRoute,
} as any)
const AgentsStitchRoute = AgentsStitchRouteImport.update({
  id: '/stitch',
  path: '/stitch',
  getParentRoute: () => AgentsRoute,
} as any)
const AgentsSkillsRoute = AgentsSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AgentsRoute,
} as any)
const AgentsClaudeRoute = AgentsClaudeRouteImport.update({
  id: '/claude',
  path: '/claude',
  getParentRoute: () => AgentsRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNewProjectRoute = AuthedNewProjectRouteImport.update({
  id: '/new-project',
  path: '/new-project',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProjectIdRoute = AuthedProjectIdRouteImport.update({
  id: '/project/$id',
  path: '/project/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const PortalTokenTaskTaskIdRoute = PortalTokenTaskTaskIdRouteImport.update({
  id: '/task/$taskId',
  path: '/task/$taskId',
  getParentRoute: () => PortalTokenRoute,
} as any)
const AuthedProjectIdStitchRoute = AuthedProjectIdStitchRouteImport.update({
  id: '/stitch',
  path: '/stitch',
  getParentRoute: () => AuthedProjectIdRoute,
} as any)
const AuthedProjectIdTaskTaskIdRoute =
  AuthedProjectIdTaskTaskIdRouteImport.update({
    id: '/task/$taskId',
    path: '/task/$taskId',
    getParentRoute: () => AuthedProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/docs': typeof DocsRoute
  '/openclaw': typeof OpenclawRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/new-project': typeof AuthedNewProjectRoute
  '/settings': typeof AuthedSettingsRoute
  '/agents/claude': typeof AgentsClaudeRoute
  '/agents/skills': typeof AgentsSkillsRoute
  '/agents/stitch': typeof AgentsStitchRoute
  '/auth/desktop': typeof AuthDesktopRoute
  '/billing/return': typeof BillingReturnRoute
  '/download/mac': typeof DownloadMacRoute
  '/help/import-transactions-via-google-sheets': typeof HelpImportTransactionsViaGoogleSheetsRoute
  '/portal/$token': typeof PortalTokenRouteWithChildren
  '/agents/': typeof AgentsIndexRoute
  '/project/$id': typeof AuthedProjectIdRouteWithChildren
  '/project/$id/stitch': typeof AuthedProjectIdStitchRoute
  '/portal/$token/task/$taskId': typeof PortalTokenTaskTaskIdRoute
  '/project/$id/task/$taskId': typeof AuthedProjectIdTaskTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/docs': typeof DocsRoute
  '/openclaw': typeof OpenclawRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/new-project': typeof AuthedNewProjectRoute
  '/settings': typeof AuthedSettingsRoute
  '/agents/claude': typeof AgentsClaudeRoute
  '/agents/skills': typeof AgentsSkillsRoute
  '/agents/stitch': typeof AgentsStitchRoute
  '/auth/desktop': typeof AuthDesktopRoute
  '/billing/return': typeof BillingReturnRoute
  '/download/mac': typeof DownloadMacRoute
  '/help/import-transactions-via-google-sheets': typeof HelpImportTransactionsViaGoogleSheetsRoute
  '/portal/$token': typeof PortalTokenRouteWithChildren
  '/agents': typeof AgentsIndexRoute
  '/project/$id': typeof AuthedProjectIdRouteWithChildren
  '/project/$id/stitch': typeof AuthedProjectIdStitchRoute
  '/portal/$token/task/$taskId': typeof PortalTokenTaskTaskIdRoute
  '/project/$id/task/$taskId': typeof AuthedProjectIdTaskTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/agents': typeof AgentsRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/docs': typeof DocsRoute
  '/openclaw': typeof OpenclawRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/new-project': typeof AuthedNewProjectRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/agents/claude': typeof AgentsClaudeRoute
  '/agents/skills': typeof AgentsSkillsRoute
  '/agents/stitch': typeof AgentsStitchRoute
  '/auth/desktop': typeof AuthDesktopRoute
  '/billing/return': typeof BillingReturnRoute
  '/download/mac': typeof DownloadMacRoute
  '/help/import-transactions-via-google-sheets': typeof HelpImportTransactionsViaGoogleSheetsRoute
  '/portal/$token': typeof PortalTokenRouteWithChildren
  '/agents/': typeof AgentsIndexRoute
  '/_authed/project/$id': typeof AuthedProjectIdRouteWithChildren
  '/_authed/project/$id/stitch': typeof AuthedProjectIdStitchRoute
  '/portal/$token/task/$taskId': typeof PortalTokenTaskTaskIdRoute
  '/_authed/project/$id/task/$taskId': typeof AuthedProjectIdTaskTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/auth'
    | '/docs'
    | '/openclaw'
    | '/privacy'
    | '/terms'
    | '/dashboard'
    | '/new-project'
    | '/settings'
    | '/agents/claude'
    | '/agents/skills'
    | '/agents/stitch'
    | '/auth/desktop'
    | '/billing/return'
    | '/download/mac'
    | '/help/import-transactions-via-google-sheets'
    | '/portal/$token'
    | '/agents/'
    | '/project/$id'
    | '/project/$id/stitch'
    | '/portal/$token/task/$taskId'
    | '/project/$id/task/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/docs'
    | '/openclaw'
    | '/privacy'
    | '/terms'
    | '/dashboard'
    | '/new-project'
    | '/settings'
    | '/agents/claude'
    | '/agents/skills'
    | '/agents/stitch'
    | '/auth/desktop'
    | '/billing/return'
    | '/download/mac'
    | '/help/import-transactions-via-google-sheets'
    | '/portal/$token'
    | '/agents'
    | '/project/$id'
    | '/project/$id/stitch'
    | '/portal/$token/task/$taskId'
    | '/project/$id/task/$taskId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/agents'
    | '/auth'
    | '/docs'
    | '/openclaw'
    | '/privacy'
    | '/terms'
    | '/_authed/dashboard'
    | '/_authed/new-project'
    | '/_authed/settings'
    | '/agents/claude'
    | '/agents/skills'
    | '/agents/stitch'
    | '/auth/desktop'
    | '/billing/return'
    | '/download/mac'
    | '/help/import-transactions-via-google-sheets'
    | '/portal/$token'
    | '/agents/'
    | '/_authed/project/$id'
    | '/_authed/project/$id/stitch'
    | '/portal/$token/task/$taskId'
    | '/_authed/project/$id/task/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AgentsRoute: typeof AgentsRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DocsRoute: typeof DocsRoute
  OpenclawRoute: typeof OpenclawRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  BillingReturnRoute: typeof BillingReturnRoute
  DownloadMacRoute: typeof DownloadMacRoute
  HelpImportTransactionsViaGoogleSheetsRoute: typeof HelpImportTransactionsViaGoogleSheetsRoute
  PortalTokenRoute: typeof PortalTokenRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openclaw': {
      id: '/openclaw'
      path: '/openclaw'
      fullPath: '/openclaw'
      preLoaderRoute: typeof OpenclawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/portal/$token': {
      id: '/portal/$token'
      path: '/portal/$token'
      fullPath: '/portal/$token'
      preLoaderRoute: typeof PortalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/import-transactions-via-google-sheets': {
      id: '/help/import-transactions-via-google-sheets'
      path: '/help/import-transactions-via-google-sheets'
      fullPath: '/help/import-transactions-via-google-sheets'
      preLoaderRoute: typeof HelpImportTransactionsViaGoogleSheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/mac': {
      id: '/download/mac'
      path: '/download/mac'
      fullPath: '/download/mac'
      preLoaderRoute: typeof DownloadMacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/return': {
      id: '/billing/return'
      path: '/billing/return'
      fullPath: '/billing/return'
      preLoaderRoute: typeof BillingReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/desktop': {
      id: '/auth/desktop'
      path: '/desktop'
      fullPath: '/auth/desktop'
      preLoaderRoute: typeof AuthDesktopRouteImport
      parentRoute: typeof AuthRoute
    }
    '/agents/stitch': {
      id: '/agents/stitch'
      path: '/stitch'
      fullPath: '/agents/stitch'
      preLoaderRoute: typeof AgentsStitchRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/agents/skills': {
      id: '/agents/skills'
      path: '/skills'
      fullPath: '/agents/skills'
      preLoaderRoute: typeof AgentsSkillsRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/agents/claude': {
      id: '/agents/claude'
      path: '/claude'
      fullPath: '/agents/claude'
      preLoaderRoute: typeof AgentsClaudeRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/new-project': {
      id: '/_authed/new-project'
      path: '/new-project'
      fullPath: '/new-project'
      preLoaderRoute: typeof AuthedNewProjectRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/project/$id': {
      id: '/_authed/project/$id'
      path: '/project/$id'
      fullPath: '/project/$id'
      preLoaderRoute: typeof AuthedProjectIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/portal/$token/task/$taskId': {
      id: '/portal/$token/task/$taskId'
      path: '/task/$taskId'
      fullPath: '/portal/$token/task/$taskId'
      preLoaderRoute: typeof PortalTokenTaskTaskIdRouteImport
      parentRoute: typeof PortalTokenRoute
    }
    '/_authed/project/$id/stitch': {
      id: '/_authed/project/$id/stitch'
      path: '/stitch'
      fullPath: '/project/$id/stitch'
      preLoaderRoute: typeof AuthedProjectIdStitchRouteImport
      parentRoute: typeof AuthedProjectIdRoute
    }
    '/_authed/project/$id/task/$taskId': {
      id: '/_authed/project/$id/task/$taskId'
      path: '/task/$taskId'
      fullPath: '/project/$id/task/$taskId'
      preLoaderRoute: typeof AuthedProjectIdTaskTaskIdRouteImport
      parentRoute: typeof AuthedProjectIdRoute
    }
  }
}

interface AuthedProjectIdRouteChildren {
  AuthedProjectIdStitchRoute: typeof AuthedProjectIdStitchRoute
  AuthedProjectIdTaskTaskIdRoute: typeof AuthedProjectIdTaskTaskIdRoute
}

const AuthedProjectIdRouteChildren: AuthedProjectIdRouteChildren = {
  AuthedProjectIdStitchRoute: AuthedProjectIdStitchRoute,
  AuthedProjectIdTaskTaskIdRoute: AuthedProjectIdTaskTaskIdRoute,
}

const AuthedProjectIdRouteWithChildren = AuthedProjectIdRoute._addFileChildren(
  AuthedProjectIdRouteChildren,
)

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedNewProjectRoute: typeof AuthedNewProjectRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedProjectIdRoute: typeof AuthedProjectIdRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedNewProjectRoute: AuthedNewProjectRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedProjectIdRoute: AuthedProjectIdRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface AgentsRouteChildren {
  AgentsClaudeRoute: typeof AgentsClaudeRoute
  AgentsSkillsRoute: typeof AgentsSkillsRoute
  AgentsStitchRoute: typeof AgentsStitchRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsClaudeRoute: AgentsClaudeRoute,
  AgentsSkillsRoute: AgentsSkillsRoute,
  AgentsStitchRoute: AgentsStitchRoute,
  AgentsIndexRoute: AgentsIndexRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface AuthRouteChildren {
  AuthDesktopRoute: typeof AuthDesktopRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDesktopRoute: AuthDesktopRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PortalTokenRouteChildren {
  PortalTokenTaskTaskIdRoute: typeof PortalTokenTaskTaskIdRoute
}

const PortalTokenRouteChildren: PortalTokenRouteChildren = {
  PortalTokenTaskTaskIdRoute: PortalTokenTaskTaskIdRoute,
}

const PortalTokenRouteWithChildren = PortalTokenRoute._addFileChildren(
  PortalTokenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AgentsRoute: AgentsRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DocsRoute: DocsRoute,
  OpenclawRoute: OpenclawRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  BillingReturnRoute: BillingReturnRoute,
  DownloadMacRoute: DownloadMacRoute,
  HelpImportTransactionsViaGoogleSheetsRoute:
    HelpImportTransactionsViaGoogleSheetsRoute,
  PortalTokenRoute: PortalTokenRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
