export const IPC_CHANNELS = {
  authOpenLogin: "auth:open-login",
  authLogout: "auth:logout",
  authGetSession: "auth:get-session",
  authSessionChanged: "auth:session-changed",
  projectContextGetSelected: "project-context:get-selected",
  desktopApiListProjects: "desktop-api:list-projects",
  desktopApiGetProject: "desktop-api:get-project",
  desktopApiListProjectPhases: "desktop-api:list-project-phases",
  desktopApiListPhaseTasks: "desktop-api:list-phase-tasks",
  desktopApiListUserTasks: "desktop-api:list-user-tasks",
  desktopApiCreateTask: "desktop-api:create-task",
  desktopApiDeleteTask: "desktop-api:delete-task",
  desktopApiSetTaskPriority: "desktop-api:set-task-priority",
  engineGetStatus: "engine:get-status",
  companionShow: "companion:show",
  companionHide: "companion:hide",
  companionSetState: "companion:set-state",
  companionSetInteractive: "companion:set-interactive",
  windowToggleMaximize: "window:toggle-maximize",
  screenGetActiveApp: "screen:get-active-app",
  screenCaptureActiveWindow: "screen:capture-active-window",
  permissionsGetStatus: "permissions:get-status",
  permissionsOpenSystemSettings: "permissions:open-system-settings",
  shellOpenExternal: "shell:open-external",
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
