export const IPC_CHANNELS = {
  authOpenLogin: "auth:open-login",
  authLogout: "auth:logout",
  authGetSession: "auth:get-session",
  authGetAccessToken: "auth:get-access-token",
  authSessionChanged: "auth:session-changed",
  engineGetStatus: "engine:get-status",
  engineListProviders: "engine:list-providers",
  engineRefreshProviders: "engine:refresh-providers",
  engineUpdateProvider: "engine:update-provider",
  engineStartRun: "engine:start-run",
  engineCancelRun: "engine:cancel-run",
  engineCreateFigmaExport: "engine:create-figma-export",
  engineCreateFigJamExport: "engine:create-figjam-export",
  engineExportWireframeCode: "engine:export-wireframe-code",
  engineCreatePaperExport: "engine:create-paper-export",
  engineRunEvent: "engine:run-event",
  companionShow: "companion:show",
  companionHide: "companion:hide",
  companionSetState: "companion:set-state",
  companionSetInteractive: "companion:set-interactive",
  voiceGetStatus: "voice:get-status",
  voiceTranscribe: "voice:transcribe",
  voiceShortcutStartStopRecording: "voice:shortcut-start-stop-recording",
  voiceShortcutOpenLatestChat: "voice:shortcut-open-latest-chat",
  windowToggleMaximize: "window:toggle-maximize",
  screenGetActiveApp: "screen:get-active-app",
  screenCaptureActiveWindow: "screen:capture-active-window",
  permissionsGetStatus: "permissions:get-status",
  permissionsRequestMicrophone: "permissions:request-microphone",
  permissionsOpenSystemSettings: "permissions:open-system-settings",
  shellOpenExternal: "shell:open-external",
  integrationsGetOAuthReturnUrl: "integrations:get-oauth-return-url",
  integrationOAuthCompleted: "integration:oauth-completed",
  updatesGetStatus: "updates:get-status",
  updatesCheck: "updates:check",
  updatesInstall: "updates:install",
  updatesStatusChanged: "updates:status-changed",
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
