/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedTasksRouteImport } from './routes/_authed/tasks'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedProjectsRouteImport } from './routes/_authed/projects'
import { Route as AuthedIntegrationsRouteImport } from './routes/_authed/integrations'
import { Route as AuthedSubscriptionsRouteImport } from './routes/_authed/subscriptions'
import { Route as AuthedClientPortalRouteImport } from './routes/_authed/client-portal'
import { Route as AuthedTasksTaskIdRouteImport } from './routes/_authed/tasks.$taskId'
import { Route as AuthedSettingsPortalRouteImport } from './routes/_authed/settings.portal'
import { Route as AuthedSettingsDeveloperRouteImport } from './routes/_authed/settings.developer'
import { Route as AuthedSettingsShortcutsRouteImport } from './routes/_authed/settings.shortcuts'
import { Route as AuthedSettingsClientsRouteImport } from './routes/_authed/settings.clients'
import { Route as AuthedSettingsBillingRouteImport } from './routes/_authed/settings.billing'
import { Route as AuthedSettingsAccountRouteImport } from './routes/_authed/settings.account'
import { Route as AuthedProjectsCreateRouteImport } from './routes/_authed/projects.create'
import { Route as AuthedProjectProjectIdRouteImport } from './routes/_authed/project.$projectId'
import { Route as AuthedAgentsClaudeRouteImport } from './routes/_authed/agents.claude'
import { Route as AuthedProjectProjectIdDetailsRouteImport } from './routes/_authed/project.$projectId.details'
import { Route as AuthedClientPortalProjectIdPreviewRouteImport } from './routes/_authed/client-portal.$projectId.preview'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTasksRoute = AuthedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProjectsRoute = AuthedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIntegrationsRoute = AuthedIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSubscriptionsRoute = AuthedSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedClientPortalRoute = AuthedClientPortalRouteImport.update({
  id: '/client-portal',
  path: '/client-portal',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTasksTaskIdRoute = AuthedTasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => AuthedTasksRoute,
} as any)
const AuthedSettingsPortalRoute = AuthedSettingsPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsDeveloperRoute = AuthedSettingsDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsShortcutsRoute = AuthedSettingsShortcutsRouteImport.update({
  id: '/shortcuts',
  path: '/shortcuts',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsClientsRoute = AuthedSettingsClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsBillingRoute = AuthedSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsAccountRoute = AuthedSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedProjectsCreateRoute = AuthedProjectsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthedProjectsRoute,
} as any)
const AuthedProjectProjectIdRoute = AuthedProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAgentsClaudeRoute = AuthedAgentsClaudeRouteImport.update({
  id: '/agents/claude',
  path: '/agents/claude',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProjectProjectIdDetailsRoute =
  AuthedProjectProjectIdDetailsRouteImport.update({
    id: '/details',
    path: '/details',
    getParentRoute: () => AuthedProjectProjectIdRoute,
  } as any)
const AuthedClientPortalProjectIdPreviewRoute =
  AuthedClientPortalProjectIdPreviewRouteImport.update({
    id: '/$projectId/preview',
    path: '/$projectId/preview',
    getParentRoute: () => AuthedClientPortalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/auth': typeof AuthRoute
  '/client-portal': typeof AuthedClientPortalRouteWithChildren
  '/integrations': typeof AuthedIntegrationsRoute
  '/subscriptions': typeof AuthedSubscriptionsRoute
  '/projects': typeof AuthedProjectsRouteWithChildren
  '/settings': typeof AuthedSettingsRouteWithChildren
  '/tasks': typeof AuthedTasksRouteWithChildren
  '/agents/claude': typeof AuthedAgentsClaudeRoute
  '/project/$projectId': typeof AuthedProjectProjectIdRouteWithChildren
  '/projects/create': typeof AuthedProjectsCreateRoute
  '/settings/account': typeof AuthedSettingsAccountRoute
  '/settings/billing': typeof AuthedSettingsBillingRoute
  '/settings/clients': typeof AuthedSettingsClientsRoute
  '/settings/developer': typeof AuthedSettingsDeveloperRoute
  '/settings/shortcuts': typeof AuthedSettingsShortcutsRoute
  '/settings/portal': typeof AuthedSettingsPortalRoute
  '/tasks/$taskId': typeof AuthedTasksTaskIdRoute
  '/client-portal/$projectId/preview': typeof AuthedClientPortalProjectIdPreviewRoute
  '/project/$projectId/details': typeof AuthedProjectProjectIdDetailsRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/client-portal': typeof AuthedClientPortalRouteWithChildren
  '/integrations': typeof AuthedIntegrationsRoute
  '/subscriptions': typeof AuthedSubscriptionsRoute
  '/projects': typeof AuthedProjectsRouteWithChildren
  '/settings': typeof AuthedSettingsRouteWithChildren
  '/tasks': typeof AuthedTasksRouteWithChildren
  '/': typeof AuthedIndexRoute
  '/agents/claude': typeof AuthedAgentsClaudeRoute
  '/project/$projectId': typeof AuthedProjectProjectIdRouteWithChildren
  '/projects/create': typeof AuthedProjectsCreateRoute
  '/settings/account': typeof AuthedSettingsAccountRoute
  '/settings/billing': typeof AuthedSettingsBillingRoute
  '/settings/clients': typeof AuthedSettingsClientsRoute
  '/settings/developer': typeof AuthedSettingsDeveloperRoute
  '/settings/shortcuts': typeof AuthedSettingsShortcutsRoute
  '/settings/portal': typeof AuthedSettingsPortalRoute
  '/tasks/$taskId': typeof AuthedTasksTaskIdRoute
  '/client-portal/$projectId/preview': typeof AuthedClientPortalProjectIdPreviewRoute
  '/project/$projectId/details': typeof AuthedProjectProjectIdDetailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authed/client-portal': typeof AuthedClientPortalRouteWithChildren
  '/_authed/integrations': typeof AuthedIntegrationsRoute
  '/_authed/subscriptions': typeof AuthedSubscriptionsRoute
  '/_authed/projects': typeof AuthedProjectsRouteWithChildren
  '/_authed/settings': typeof AuthedSettingsRouteWithChildren
  '/_authed/tasks': typeof AuthedTasksRouteWithChildren
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/agents/claude': typeof AuthedAgentsClaudeRoute
  '/_authed/project/$projectId': typeof AuthedProjectProjectIdRouteWithChildren
  '/_authed/projects/create': typeof AuthedProjectsCreateRoute
  '/_authed/settings/account': typeof AuthedSettingsAccountRoute
  '/_authed/settings/billing': typeof AuthedSettingsBillingRoute
  '/_authed/settings/clients': typeof AuthedSettingsClientsRoute
  '/_authed/settings/developer': typeof AuthedSettingsDeveloperRoute
  '/_authed/settings/shortcuts': typeof AuthedSettingsShortcutsRoute
  '/_authed/settings/portal': typeof AuthedSettingsPortalRoute
  '/_authed/tasks/$taskId': typeof AuthedTasksTaskIdRoute
  '/_authed/client-portal/$projectId/preview': typeof AuthedClientPortalProjectIdPreviewRoute
  '/_authed/project/$projectId/details': typeof AuthedProjectProjectIdDetailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/client-portal'
    | '/integrations'
    | '/subscriptions'
    | '/projects'
    | '/settings'
    | '/tasks'
    | '/agents/claude'
    | '/project/$projectId'
    | '/projects/create'
    | '/settings/account'
    | '/settings/billing'
    | '/settings/clients'
    | '/settings/developer'
    | '/settings/shortcuts'
    | '/settings/portal'
    | '/tasks/$taskId'
    | '/client-portal/$projectId/preview'
    | '/project/$projectId/details'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/client-portal'
    | '/integrations'
    | '/subscriptions'
    | '/projects'
    | '/settings'
    | '/tasks'
    | '/'
    | '/agents/claude'
    | '/project/$projectId'
    | '/projects/create'
    | '/settings/account'
    | '/settings/billing'
    | '/settings/clients'
    | '/settings/developer'
    | '/settings/shortcuts'
    | '/settings/portal'
    | '/tasks/$taskId'
    | '/client-portal/$projectId/preview'
    | '/project/$projectId/details'
  id:
    | '__root__'
    | '/_authed'
    | '/auth'
    | '/_authed/client-portal'
    | '/_authed/integrations'
    | '/_authed/subscriptions'
    | '/_authed/projects'
    | '/_authed/settings'
    | '/_authed/tasks'
    | '/_authed/'
    | '/_authed/agents/claude'
    | '/_authed/project/$projectId'
    | '/_authed/projects/create'
    | '/_authed/settings/account'
    | '/_authed/settings/billing'
    | '/_authed/settings/clients'
    | '/_authed/settings/developer'
    | '/_authed/settings/shortcuts'
    | '/_authed/settings/portal'
    | '/_authed/tasks/$taskId'
    | '/_authed/client-portal/$projectId/preview'
    | '/_authed/project/$projectId/details'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tasks': {
      id: '/_authed/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthedTasksRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/projects': {
      id: '/_authed/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthedProjectsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/integrations': {
      id: '/_authed/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthedIntegrationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/subscriptions': {
      id: '/_authed/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AuthedSubscriptionsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/client-portal': {
      id: '/_authed/client-portal'
      path: '/client-portal'
      fullPath: '/client-portal'
      preLoaderRoute: typeof AuthedClientPortalRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tasks/$taskId': {
      id: '/_authed/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AuthedTasksTaskIdRouteImport
      parentRoute: typeof AuthedTasksRoute
    }
    '/_authed/settings/portal': {
      id: '/_authed/settings/portal'
      path: '/portal'
      fullPath: '/settings/portal'
      preLoaderRoute: typeof AuthedSettingsPortalRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/developer': {
      id: '/_authed/settings/developer'
      path: '/developer'
      fullPath: '/settings/developer'
      preLoaderRoute: typeof AuthedSettingsDeveloperRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/shortcuts': {
      id: '/_authed/settings/shortcuts'
      path: '/shortcuts'
      fullPath: '/settings/shortcuts'
      preLoaderRoute: typeof AuthedSettingsShortcutsRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/clients': {
      id: '/_authed/settings/clients'
      path: '/clients'
      fullPath: '/settings/clients'
      preLoaderRoute: typeof AuthedSettingsClientsRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/billing': {
      id: '/_authed/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AuthedSettingsBillingRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/account': {
      id: '/_authed/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthedSettingsAccountRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/projects/create': {
      id: '/_authed/projects/create'
      path: '/create'
      fullPath: '/projects/create'
      preLoaderRoute: typeof AuthedProjectsCreateRouteImport
      parentRoute: typeof AuthedProjectsRoute
    }
    '/_authed/project/$projectId': {
      id: '/_authed/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof AuthedProjectProjectIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/agents/claude': {
      id: '/_authed/agents/claude'
      path: '/agents/claude'
      fullPath: '/agents/claude'
      preLoaderRoute: typeof AuthedAgentsClaudeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/project/$projectId/details': {
      id: '/_authed/project/$projectId/details'
      path: '/details'
      fullPath: '/project/$projectId/details'
      preLoaderRoute: typeof AuthedProjectProjectIdDetailsRouteImport
      parentRoute: typeof AuthedProjectProjectIdRoute
    }
    '/_authed/client-portal/$projectId/preview': {
      id: '/_authed/client-portal/$projectId/preview'
      path: '/$projectId/preview'
      fullPath: '/client-portal/$projectId/preview'
      preLoaderRoute: typeof AuthedClientPortalProjectIdPreviewRouteImport
      parentRoute: typeof AuthedClientPortalRoute
    }
  }
}

interface AuthedClientPortalRouteChildren {
  AuthedClientPortalProjectIdPreviewRoute: typeof AuthedClientPortalProjectIdPreviewRoute
}

const AuthedClientPortalRouteChildren: AuthedClientPortalRouteChildren = {
  AuthedClientPortalProjectIdPreviewRoute:
    AuthedClientPortalProjectIdPreviewRoute,
}

const AuthedClientPortalRouteWithChildren =
  AuthedClientPortalRoute._addFileChildren(AuthedClientPortalRouteChildren)

interface AuthedProjectsRouteChildren {
  AuthedProjectsCreateRoute: typeof AuthedProjectsCreateRoute
}

const AuthedProjectsRouteChildren: AuthedProjectsRouteChildren = {
  AuthedProjectsCreateRoute: AuthedProjectsCreateRoute,
}

const AuthedProjectsRouteWithChildren = AuthedProjectsRoute._addFileChildren(
  AuthedProjectsRouteChildren,
)

interface AuthedSettingsRouteChildren {
  AuthedSettingsAccountRoute: typeof AuthedSettingsAccountRoute
  AuthedSettingsBillingRoute: typeof AuthedSettingsBillingRoute
  AuthedSettingsClientsRoute: typeof AuthedSettingsClientsRoute
  AuthedSettingsDeveloperRoute: typeof AuthedSettingsDeveloperRoute
  AuthedSettingsShortcutsRoute: typeof AuthedSettingsShortcutsRoute
  AuthedSettingsPortalRoute: typeof AuthedSettingsPortalRoute
}

const AuthedSettingsRouteChildren: AuthedSettingsRouteChildren = {
  AuthedSettingsAccountRoute: AuthedSettingsAccountRoute,
  AuthedSettingsBillingRoute: AuthedSettingsBillingRoute,
  AuthedSettingsClientsRoute: AuthedSettingsClientsRoute,
  AuthedSettingsDeveloperRoute: AuthedSettingsDeveloperRoute,
  AuthedSettingsShortcutsRoute: AuthedSettingsShortcutsRoute,
  AuthedSettingsPortalRoute: AuthedSettingsPortalRoute,
}

const AuthedSettingsRouteWithChildren = AuthedSettingsRoute._addFileChildren(
  AuthedSettingsRouteChildren,
)

interface AuthedTasksRouteChildren {
  AuthedTasksTaskIdRoute: typeof AuthedTasksTaskIdRoute
}

const AuthedTasksRouteChildren: AuthedTasksRouteChildren = {
  AuthedTasksTaskIdRoute: AuthedTasksTaskIdRoute,
}

const AuthedTasksRouteWithChildren = AuthedTasksRoute._addFileChildren(
  AuthedTasksRouteChildren,
)

interface AuthedProjectProjectIdRouteChildren {
  AuthedProjectProjectIdDetailsRoute: typeof AuthedProjectProjectIdDetailsRoute
}

const AuthedProjectProjectIdRouteChildren: AuthedProjectProjectIdRouteChildren =
  {
    AuthedProjectProjectIdDetailsRoute: AuthedProjectProjectIdDetailsRoute,
  }

const AuthedProjectProjectIdRouteWithChildren =
  AuthedProjectProjectIdRoute._addFileChildren(
    AuthedProjectProjectIdRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedClientPortalRoute: typeof AuthedClientPortalRouteWithChildren
  AuthedIntegrationsRoute: typeof AuthedIntegrationsRoute
  AuthedSubscriptionsRoute: typeof AuthedSubscriptionsRoute
  AuthedProjectsRoute: typeof AuthedProjectsRouteWithChildren
  AuthedSettingsRoute: typeof AuthedSettingsRouteWithChildren
  AuthedTasksRoute: typeof AuthedTasksRouteWithChildren
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedAgentsClaudeRoute: typeof AuthedAgentsClaudeRoute
  AuthedProjectProjectIdRoute: typeof AuthedProjectProjectIdRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedClientPortalRoute: AuthedClientPortalRouteWithChildren,
  AuthedIntegrationsRoute: AuthedIntegrationsRoute,
  AuthedSubscriptionsRoute: AuthedSubscriptionsRoute,
  AuthedProjectsRoute: AuthedProjectsRouteWithChildren,
  AuthedSettingsRoute: AuthedSettingsRouteWithChildren,
  AuthedTasksRoute: AuthedTasksRouteWithChildren,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedAgentsClaudeRoute: AuthedAgentsClaudeRoute,
  AuthedProjectProjectIdRoute: AuthedProjectProjectIdRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
