import { useState } from "react";
import { cn } from "@/lib/utils";
import testimonials from "@/marketing/testimonials.json";
export function AuthTestimonialCarousel({variant="desktop",className}:{variant?:"desktop"|"mobile";className?:string}) {
 const [active,setActive]=useState(()=>Math.max(0,testimonials.findIndex(t=>t.name==='Adrien Ninet')));
 return <div tabIndex={0} role="region" aria-label="Customer testimonials. Use left and right arrow keys to browse." onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();setActive(i=>(i+(e.key==='ArrowRight'?1:testimonials.length-1))%testimonials.length)}}} className={cn('relative overflow-hidden rounded-[8px] bg-[#cfccfb]',variant==='mobile'?'h-[400px] w-full shrink-0':'h-full w-full',className)}>
  <div aria-hidden="true" className="absolute inset-0 overflow-hidden"><img src="/auth/signup-brand.png" alt="" className="absolute max-w-none" style={{width:'254.859%',height:'231.238%',left:'-77.373%',top:'-65.588%'}}/><div className="absolute inset-0 opacity-40" style={{backgroundImage:'url(/auth/signup-noise.png)',backgroundRepeat:'repeat'}}/></div>
  <div className="absolute inset-0 flex items-center justify-center"><div className="flex items-stretch justify-center gap-4">{[-1,0,1].map(offset=>{const t=testimonials[(active+offset+testimonials.length)%testimonials.length]!;return <article key={offset} className={cn('shrink-0 flex-col rounded-[12px] bg-white shadow-[0_1px_1px_rgba(0,0,0,0.4)] w-[min(428px,calc(100vw-64px))] min-h-[215px] p-6',offset===0?'flex':'hidden lg:flex opacity-50 backdrop-blur-[40.5px]')}><div className="flex items-center gap-2"><img src={t.avatarSrc} alt="" width={36} height={37} className="h-[37px] w-9 shrink-0 rounded-full object-cover"/><div className="min-w-0"><p className="truncate text-[13px] font-medium leading-[1.5] text-[#0A0A0A]">{t.name}</p><p className="truncate text-[13px] font-medium leading-[1.5] text-[#737373]">{t.role}</p></div></div><p className="mt-3 text-[15px] font-semibold leading-[1.5] text-[#171717]">“{t.quote}”</p></article>})}</div></div>
 </div>;
}
