/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OpenclawRouteImport } from './routes/openclaw'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalTokenRouteImport } from './routes/portal.$token'
import { Route as HelpImportTransactionsViaGoogleSheetsRouteImport } from './routes/help/import-transactions-via-google-sheets'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedNewProjectRouteImport } from './routes/_authed/new-project'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedProjectIdRouteImport } from './routes/_authed/project.$id'
import { Route as PortalTokenTaskTaskIdRouteImport } from './routes/portal.$token.task.$taskId'
import { Route as AuthedProjectIdTaskTaskIdRouteImport } from './routes/_authed/project.$id.task.$taskId'

const OpenclawRoute = OpenclawRouteImport.update({
  id: '/openclaw',
  path: '/openclaw',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTokenRoute = PortalTokenRouteImport.update({
  id: '/portal/$token',
  path: '/portal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpImportTransactionsViaGoogleSheetsRoute =
  HelpImportTransactionsViaGoogleSheetsRouteImport.update({
    id: '/help/import-transactions-via-google-sheets',
    path: '/help/import-transactions-via-google-sheets',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNewProjectRoute = AuthedNewProjectRouteImport.update({
  id: '/new-project',
  path: '/new-project',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProjectIdRoute = AuthedProjectIdRouteImport.update({
  id: '/project/$id',
  path: '/project/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const PortalTokenTaskTaskIdRoute = PortalTokenTaskTaskIdRouteImport.update({
  id: '/task/$taskId',
  path: '/task/$taskId',
  getParentRoute: () => PortalTokenRoute,
} as any)
const AuthedProjectIdTaskTaskIdRoute =
  AuthedProjectIdTaskTaskIdRouteImport.update({
    id: '/task/$taskId',
    path: '/task/$taskId',
    getParentRoute: () => AuthedProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/openclaw': typeof OpenclawRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/new-project': typeof AuthedNewProjectRoute
  '/settings': typeof AuthedSettingsRoute
  '/help/import-transactions-via-google-sheets': typeof HelpImportTransactionsViaGoogleSheetsRoute
  '/portal/$token': typeof PortalTokenRouteWithChildren
  '/project/$id': typeof AuthedProjectIdRouteWithChildren
  '/portal/$token/task/$taskId': typeof PortalTokenTaskTaskIdRoute
  '/project/$id/task/$taskId': typeof AuthedProjectIdTaskTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/openclaw': typeof OpenclawRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/new-project': typeof AuthedNewProjectRoute
  '/settings': typeof AuthedSettingsRoute
  '/help/import-transactions-via-google-sheets': typeof HelpImportTransactionsViaGoogleSheetsRoute
  '/portal/$token': typeof PortalTokenRouteWithChildren
  '/project/$id': typeof AuthedProjectIdRouteWithChildren
  '/portal/$token/task/$taskId': typeof PortalTokenTaskTaskIdRoute
  '/project/$id/task/$taskId': typeof AuthedProjectIdTaskTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/openclaw': typeof OpenclawRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/new-project': typeof AuthedNewProjectRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/help/import-transactions-via-google-sheets': typeof HelpImportTransactionsViaGoogleSheetsRoute
  '/portal/$token': typeof PortalTokenRouteWithChildren
  '/_authed/project/$id': typeof AuthedProjectIdRouteWithChildren
  '/portal/$token/task/$taskId': typeof PortalTokenTaskTaskIdRoute
  '/_authed/project/$id/task/$taskId': typeof AuthedProjectIdTaskTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/docs'
    | '/openclaw'
    | '/dashboard'
    | '/new-project'
    | '/settings'
    | '/help/import-transactions-via-google-sheets'
    | '/portal/$token'
    | '/project/$id'
    | '/portal/$token/task/$taskId'
    | '/project/$id/task/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/docs'
    | '/openclaw'
    | '/dashboard'
    | '/new-project'
    | '/settings'
    | '/help/import-transactions-via-google-sheets'
    | '/portal/$token'
    | '/project/$id'
    | '/portal/$token/task/$taskId'
    | '/project/$id/task/$taskId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/auth'
    | '/docs'
    | '/openclaw'
    | '/_authed/dashboard'
    | '/_authed/new-project'
    | '/_authed/settings'
    | '/help/import-transactions-via-google-sheets'
    | '/portal/$token'
    | '/_authed/project/$id'
    | '/portal/$token/task/$taskId'
    | '/_authed/project/$id/task/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthRoute: typeof AuthRoute
  DocsRoute: typeof DocsRoute
  OpenclawRoute: typeof OpenclawRoute
  HelpImportTransactionsViaGoogleSheetsRoute: typeof HelpImportTransactionsViaGoogleSheetsRoute
  PortalTokenRoute: typeof PortalTokenRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/openclaw': {
      id: '/openclaw'
      path: '/openclaw'
      fullPath: '/openclaw'
      preLoaderRoute: typeof OpenclawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$token': {
      id: '/portal/$token'
      path: '/portal/$token'
      fullPath: '/portal/$token'
      preLoaderRoute: typeof PortalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/import-transactions-via-google-sheets': {
      id: '/help/import-transactions-via-google-sheets'
      path: '/help/import-transactions-via-google-sheets'
      fullPath: '/help/import-transactions-via-google-sheets'
      preLoaderRoute: typeof HelpImportTransactionsViaGoogleSheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/new-project': {
      id: '/_authed/new-project'
      path: '/new-project'
      fullPath: '/new-project'
      preLoaderRoute: typeof AuthedNewProjectRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/project/$id': {
      id: '/_authed/project/$id'
      path: '/project/$id'
      fullPath: '/project/$id'
      preLoaderRoute: typeof AuthedProjectIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/portal/$token/task/$taskId': {
      id: '/portal/$token/task/$taskId'
      path: '/task/$taskId'
      fullPath: '/portal/$token/task/$taskId'
      preLoaderRoute: typeof PortalTokenTaskTaskIdRouteImport
      parentRoute: typeof PortalTokenRoute
    }
    '/_authed/project/$id/task/$taskId': {
      id: '/_authed/project/$id/task/$taskId'
      path: '/task/$taskId'
      fullPath: '/project/$id/task/$taskId'
      preLoaderRoute: typeof AuthedProjectIdTaskTaskIdRouteImport
      parentRoute: typeof AuthedProjectIdRoute
    }
  }
}

interface AuthedProjectIdRouteChildren {
  AuthedProjectIdTaskTaskIdRoute: typeof AuthedProjectIdTaskTaskIdRoute
}

const AuthedProjectIdRouteChildren: AuthedProjectIdRouteChildren = {
  AuthedProjectIdTaskTaskIdRoute: AuthedProjectIdTaskTaskIdRoute,
}

const AuthedProjectIdRouteWithChildren = AuthedProjectIdRoute._addFileChildren(
  AuthedProjectIdRouteChildren,
)

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedNewProjectRoute: typeof AuthedNewProjectRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedProjectIdRoute: typeof AuthedProjectIdRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedNewProjectRoute: AuthedNewProjectRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedProjectIdRoute: AuthedProjectIdRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface PortalTokenRouteChildren {
  PortalTokenTaskTaskIdRoute: typeof PortalTokenTaskTaskIdRoute
}

const PortalTokenRouteChildren: PortalTokenRouteChildren = {
  PortalTokenTaskTaskIdRoute: PortalTokenTaskTaskIdRoute,
}

const PortalTokenRouteWithChildren = PortalTokenRoute._addFileChildren(
  PortalTokenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AuthRoute: AuthRoute,
  DocsRoute: DocsRoute,
  OpenclawRoute: OpenclawRoute,
  HelpImportTransactionsViaGoogleSheetsRoute:
    HelpImportTransactionsViaGoogleSheetsRoute,
  PortalTokenRoute: PortalTokenRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
