/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalTokenRouteImport } from './routes/portal.$token'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppNewProjectRouteImport } from './routes/_app/new-project'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppProjectIdRouteImport } from './routes/_app/project.$id'
import { Route as AppProjectIdTaskTaskIdRouteImport } from './routes/_app/project.$id.task.$taskId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTokenRoute = PortalTokenRouteImport.update({
  id: '/portal/$token',
  path: '/portal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppNewProjectRoute = AppNewProjectRouteImport.update({
  id: '/new-project',
  path: '/new-project',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectIdRoute = AppProjectIdRouteImport.update({
  id: '/project/$id',
  path: '/project/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectIdTaskTaskIdRoute = AppProjectIdTaskTaskIdRouteImport.update({
  id: '/task/$taskId',
  path: '/task/$taskId',
  getParentRoute: () => AppProjectIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AppDashboardRoute
  '/new-project': typeof AppNewProjectRoute
  '/settings': typeof AppSettingsRoute
  '/portal/$token': typeof PortalTokenRoute
  '/project/$id': typeof AppProjectIdRouteWithChildren
  '/project/$id/task/$taskId': typeof AppProjectIdTaskTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AppDashboardRoute
  '/new-project': typeof AppNewProjectRoute
  '/settings': typeof AppSettingsRoute
  '/portal/$token': typeof PortalTokenRoute
  '/project/$id': typeof AppProjectIdRouteWithChildren
  '/project/$id/task/$taskId': typeof AppProjectIdTaskTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/new-project': typeof AppNewProjectRoute
  '/_app/settings': typeof AppSettingsRoute
  '/portal/$token': typeof PortalTokenRoute
  '/_app/project/$id': typeof AppProjectIdRouteWithChildren
  '/_app/project/$id/task/$taskId': typeof AppProjectIdTaskTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/new-project'
    | '/settings'
    | '/portal/$token'
    | '/project/$id'
    | '/project/$id/task/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/new-project'
    | '/settings'
    | '/portal/$token'
    | '/project/$id'
    | '/project/$id/task/$taskId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/dashboard'
    | '/_app/new-project'
    | '/_app/settings'
    | '/portal/$token'
    | '/_app/project/$id'
    | '/_app/project/$id/task/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  PortalTokenRoute: typeof PortalTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$token': {
      id: '/portal/$token'
      path: '/portal/$token'
      fullPath: '/portal/$token'
      preLoaderRoute: typeof PortalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/new-project': {
      id: '/_app/new-project'
      path: '/new-project'
      fullPath: '/new-project'
      preLoaderRoute: typeof AppNewProjectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/project/$id': {
      id: '/_app/project/$id'
      path: '/project/$id'
      fullPath: '/project/$id'
      preLoaderRoute: typeof AppProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/project/$id/task/$taskId': {
      id: '/_app/project/$id/task/$taskId'
      path: '/task/$taskId'
      fullPath: '/project/$id/task/$taskId'
      preLoaderRoute: typeof AppProjectIdTaskTaskIdRouteImport
      parentRoute: typeof AppProjectIdRoute
    }
  }
}

interface AppProjectIdRouteChildren {
  AppProjectIdTaskTaskIdRoute: typeof AppProjectIdTaskTaskIdRoute
}

const AppProjectIdRouteChildren: AppProjectIdRouteChildren = {
  AppProjectIdTaskTaskIdRoute: AppProjectIdTaskTaskIdRoute,
}

const AppProjectIdRouteWithChildren = AppProjectIdRoute._addFileChildren(
  AppProjectIdRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppNewProjectRoute: typeof AppNewProjectRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppProjectIdRoute: typeof AppProjectIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppNewProjectRoute: AppNewProjectRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppProjectIdRoute: AppProjectIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  PortalTokenRoute: PortalTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
