import { useEffect, useId, useRef, useState } from "react";
import { UserCircle, UploadSimple, X, Check, Plus } from "@phosphor-icons/react";
import type { ProfileInput } from "./MarketplaceState";
import { roleOptions, contacts, techId } from "./profileModel";
import { technologyGroups } from "@/marketing/marketplace/technologies";

export function RolePicker({value,onChange,initiallyOpen=true,profileStyle=false}:{value:string[];onChange:(value:string[])=>void;initiallyOpen?:boolean;profileStyle?:boolean}) {
 const [editing,setEditing]=useState(initiallyOpen);const id=useId();
 if(profileStyle)return <fieldset className="profile-role-fields"><legend>Role tags</legend><div className="role-summary-row"><div id="role-summary">{value.map(role=><span className="role-summary-tag" key={role}>{role}</span>)}{value.length===0&&<span className="role-summary-empty">Choose your roles</span>}</div><button type="button" className="market-add" id="edit-role-tags" aria-expanded={editing} aria-controls="role-options" onClick={()=>setEditing(!editing)}>{editing?'Done':'Edit tags'}</button></div><div id="role-options" hidden={!editing}>{roleOptions.map(role=>{const selected=value.includes(role);return <button type="button" className="market-add role-option" key={role} aria-pressed={selected} onClick={()=>onChange(selected?value.filter(r=>r!==role):[...value,role])}>{role}{selected?<Check size={14} weight="bold"/>:<Plus size={14} weight="bold"/>}</button>})}</div></fieldset>;
 return <fieldset className="role-picker"><legend>Role tags</legend><div className="role-picker-summary"><div className="role-picker-selected">{value.map(role=><span key={role}>{role}</span>)}{value.length===0&&<span className="role-picker-empty">Choose your roles</span>}</div><button type="button" className="role-picker-toggle" aria-expanded={editing} aria-controls={id} onClick={()=>setEditing(!editing)}>{editing?'Done':'Edit'}</button></div>{editing&&<div className="role-picker-options" id={id}>{roleOptions.map(role=>{const selected=value.includes(role);return <button type="button" key={role} aria-pressed={selected} onClick={()=>onChange(selected?value.filter(r=>r!==role):[...value,role])}>{role}{selected?<Check size={14} weight="bold"/>:<Plus size={14} weight="bold"/>}</button>})}</div>}</fieldset>;
}
export function contactError(key: string, value: string) {
 if (!value) return '';
 if (key === 'email') return /^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(value) && value.length <= 254 ? '' : 'Enter a valid public contact email.';
 try { const url = new URL(value); if (url.protocol === 'https:' && !url.username && !url.password && value.length <= 500) return ''; } catch {}
 return 'Enter a valid HTTPS link.';
}
export function ContactFields({draft,onChange,profileStyle=false}:{draft:ProfileInput;onChange:(draft:ProfileInput)=>void;profileStyle?:boolean}) {
 const [open,setOpen]=useState<string|null>(null); const id=useId();
 const contactFields=useRef<HTMLFieldSetElement>(null);
 useEffect(()=>{
  if(!open)return;
  const field=contactFields.current?.querySelector<HTMLElement>(`[data-contact="${open}"]`);
  field?.querySelector<HTMLInputElement>('input')?.focus({preventScroll:true});
  field?.scrollIntoView({block:'nearest',inline:'nearest',behavior:'auto'});
 },[open]);
 return <fieldset ref={contactFields} className={profileStyle?"profile-contact-fields":undefined}><legend>Contact links</legend>{profileStyle&&<p className="field-help">Choose a platform to add or edit its link.</p>}<div className="profile-contact-toggles">{contacts.map(({key,label,Icon})=><button type="button" key={key} aria-label={label} aria-expanded={open===key} aria-controls={`${id}-${key}`} className="market-add profile-social-toggle" onClick={()=>setOpen(open===key?null:key)}><Icon size={16} weight={key==='x'||(profileStyle&&['github','linkedin','website'].includes(key))?'fill':'regular'}/>{profileStyle&&<span>{label}</span>}{draft[key]&&(profileStyle?<Check className="contact-saved-check" size={14} weight="bold" aria-label="Link added"/>:<span aria-label="Link added">•</span>)}</button>)}</div>{contacts.map(({key,label})=>{const error=contactError(key,draft[key]);return <div className="form-field profile-contact-field" data-contact={key} hidden={open!==key&&(profileStyle||!error)} key={key}><label htmlFor={`${id}-${key}`}>{label}</label><input id={`${id}-${key}`} type={key==='email'?'email':'url'} maxLength={key==='email'?254:500} aria-invalid={!!error} aria-describedby={error?`${id}-${key}-error`:undefined} placeholder={profileStyle?({github:'https://github.com/username',x:'https://x.com/username',instagram:'https://instagram.com/username',linkedin:'https://linkedin.com/in/username',website:'https://your-site.com',email:'you@example.com'}[key]):key==='email'?'Public contact email':'https://'} value={draft[key]} onChange={e=>onChange({...draft,[key]:e.target.value})}/>{profileStyle&&key==='email'&&<small className="field-help">This address will be visible on your public profile.</small>}{error&&<p className="field-error" id={`${id}-${key}-error`}>{error}</p>}</div>})}</fieldset>;
}
export function TechnologyLabel({id}:{id:string}) {
 const name=Object.values(technologyGroups).flat().find(name=>techId(name)===id)??id;
 return <><img className="technology-logo" src={`/marketplace-assets/technologies/${id}.svg`} alt="" width={16} height={16}/>{name}</>;
}
export function TechnologyPicker({value,onChange}:{value:string[];onChange:(value:string[])=>void}) {
 const [query,setQuery]=useState('');const id=useId();
 const matches=query.trim()?Object.values(technologyGroups).flat().filter(name=>name.toLowerCase().includes(query.trim().toLowerCase())&&!value.includes(techId(name))).slice(0,8):[];
 return <div className="technology-search"><label className="sr-only" htmlFor={id}>Search technologies</label><input id={id} type="search" placeholder="Search technologies" autoComplete="off" value={query} onChange={e=>setQuery(e.target.value)}/>{matches.length>0&&<div className="technology-search-results">{matches.map(name=><button type="button" key={name} onClick={()=>{onChange([...value,techId(name)]);setQuery('')}}><TechnologyLabel id={techId(name)}/><span aria-hidden="true">+</span></button>)}</div>}{query.trim()&&matches.length===0&&<p className="form-note" role="status">No more matching technologies.</p>}{value.length>0&&<div className="technology-selected">{value.map(id=><button type="button" key={id} aria-label={`Remove ${Object.values(technologyGroups).flat().find(name=>techId(name)===id)??id}`} onClick={()=>onChange(value.filter(v=>v!==id))}><TechnologyLabel id={id}/><X size={12} weight="bold" className="chip-remove" aria-hidden="true"/></button>)}</div>}</div>;
}
export function PhotoField({value,onChange,compact=false}:{value?:string;onChange:(value:string)=>void;compact?:boolean}) {
 const input=useRef<HTMLInputElement>(null);
 const [error,setError]=useState('');const [busy,setBusy]=useState(false); const id=useId();
 async function upload(file?:File){if(!file)return;setError('');if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>2*1024*1024){setError('Choose a PNG, JPG or WebP under 2 MB.');return;}setBusy(true);try{const bitmap=await createImageBitmap(file);const canvas=document.createElement('canvas');canvas.width=256;canvas.height=256;const side=Math.min(bitmap.width,bitmap.height);canvas.getContext('2d')!.drawImage(bitmap,(bitmap.width-side)/2,(bitmap.height-side)/2,side,side,0,0,256,256);bitmap.close();const image=canvas.toDataURL('image/webp',.85);if(image.length>200000)throw Error();onChange(image);}catch{setError('This image could not be used. Try another photo.');}finally{setBusy(false)}}
 if(compact)return <div className="form-field setup-photo-field"><label id={`${id}-label`}>Profile photo <span>(optional)</span></label><div className="setup-photo-row"><button type="button" className="setup-photo-avatar" disabled={busy} aria-label={value?'Replace profile photo':'Upload profile photo'} aria-describedby={error?`${id}-error`:undefined} onClick={()=>input.current?.click()}>{value?<img src={value} alt="" width={40} height={40}/>:<UserCircle size={40}/>}</button><button type="button" className="setup-photo-reupload" disabled={busy} onClick={()=>input.current?.click()}><UploadSimple size={16}/>{value?"Reupload":"Upload photo"}</button><input ref={input} hidden type="file" accept="image/png,image/jpeg,image/webp" aria-labelledby={`${id}-label`} onChange={e=>{void upload(e.target.files?.[0]);e.target.value=''}}/>{value&&<button className="setup-photo-remove" type="button" disabled={busy} onClick={()=>onChange('')}>Remove</button>}</div>{error&&<p id={`${id}-error`} className="field-error" role="alert">{error}</p>}</div>;
 return <div className="form-field profile-photo-field"><label htmlFor={id}>Profile photo <span>(optional)</span></label>{value?<img src={value} alt="Profile preview" width={56} height={56} style={{borderRadius:'50%',objectFit:'cover'}}/>:<UserCircle size={56}/>}<input id={id} type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} aria-describedby={error?`${id}-error`:undefined} onChange={e=>void upload(e.target.files?.[0])}/>{error&&<p id={`${id}-error`} className="field-error" role="alert">{error}</p>}</div>;
}
